id: I6446F507
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:18:24+00:00'
last_modified: '2022-06-09T08:17:05.119096+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG0624
  title: ལམ་འབྲས་བརྒྱུད་པའི་གསོལ་འདེབས་བྲག་ཕུག་པས་མཛད་པ་ཁ་སྐོང་དང་བཅས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FF67:
      image_group_id: I1KG23245
      title: Volume 1 of liturgical texts of the sa skya pa lam 'bras tradition for
        recitation in the sgrub grwa at the new lumbini buddhist monastery
      total_pages: 180
      order: 1
      base_file: FF67.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
