id: P007982
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG0624
  title: ལམ་འབྲས་བརྒྱུད་པའི་གསོལ་འདེབས་བྲག་ཕུག་པས་མཛད་པ་ཁ་སྐོང་དང་བཅས་པ།
  author: ''
  volumes:
    0588d98257c145e5838fd96973e5ed24:
      image_group_id: I1KG23245
      title: ''
      volume_number: 1
      total_pages: 180
ebook_metadata:
  title: ལམ་འབྲས་བརྒྱུད་པའི་གསོལ་འདེབས་བྲག་ཕུག་པས་མཛད་པ་ཁ་སྐོང་དང་བཅས་པ།
  author: ''
  sku: P007982
  cover: cover.jpg
  layers:
  - pagination
