id: P007982
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:53:12.227541
source_metadata:
  id: bdr:W00KG0624
  title: ལམ་འབྲས་བརྒྱུད་པའི་གསོལ་འདེབས་བྲག་ཕུག་པས་མཛད་པ་ཁ་སྐོང་དང་བཅས་པ།
  author: ''
  volumes:
    b1dc9df1990b48ed9b84e3c060d63420:
      image_group_id: I1KG23245
      title: Volume 1 of liturgical texts of the sa skya pa lam 'bras tradition for
        recitation in the sgrub grwa at the new lumbini buddhist monastery
      volume_number: 1
      total_pages: 180
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
